# Initial Setup #

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("C:/Users/kevin/Projects/fiji-event-engagement-analytics/data/raw/fiji_fall_event_preferences.csv")

In [22]:
df.shape     # how many rows, how many columns

(43, 17)

In [23]:
df.columns      # exact column names from the Google Form

Index(['Timestamp', 'Class Year',
       'How many chapter events would you say you attended last semester? (This includes everything from B.O.B. pregames to events like Senior Sendoff)',
       'Rank how likely you are to attend each type of event:    \n\nPregames (1 = NEVER, 5 = ALWAYS)',
       'Postgames  (1 = NEVER, 5 = ALWAYS)',
       'Socials/Mixers  (1 = NEVER, 5 = ALWAYS)',
       'Brotherhood Events (fam olympics, paintball, boat trip, etc.)\n(1 = NEVER, 5 = ALWAYS)',
       'Philanthropy/Fundraising Events  \n(1 = NEVER, 5 = ALWAYS)',
       'Professional/Networking Events\n(1 = NEVER, 5 = ALWAYS)',
       'Community Service Events\n(1 = NEVER, 5 = ALWAYS)',
       'Alumni Events (pig dinner, etc.)\n(1 = NEVER, 5 = ALWAYS)',
       'What day(s) for events work best for you? (Check all that apply)',
       'What's the #1 reason you'd skip an event?',
       'How do you usually hear about events?',
       'Given the circumstances, rate your satisfaction with the  Spring semester's event lineup. (1 = Unsatisfied, 5 = Very Satisfied)',
       'Optional: One event you wish we did that we haven't?',
       'Optional: If we did more community service, what type of service would actually interest you?'],
      dtype='str')

In [24]:
df.head()

,Timestamp,Class Year,How many chapter events would you say you attended last semester? (This includes everything from B.O.B. pregames to events like Senior Sendoff),"Rank how likely you are to attend each type of event: \n\nPregames (1 = NEVER, 5 = ALWAYS)","Postgames (1 = NEVER, 5 = ALWAYS)","Socials/Mixers (1 = NEVER, 5 = ALWAYS)","Brotherhood Events (fam olympics, paintball, boat trip, etc.)\n(1 = NEVER, 5 = ALWAYS)","Philanthropy/Fundraising Events \n(1 = NEVER, 5 = ALWAYS)","Professional/Networking Events\n(1 = NEVER, 5 = ALWAYS)","Community Service Events\n(1 = NEVER, 5 = ALWAYS)","Alumni Events (pig dinner, etc.)\n(1 = NEVER, 5 = ALWAYS)",What day(s) for events work best for you? (Check all that apply),What's the #1 reason you'd skip an event?,How do you usually hear about events?,"Given the circumstances, rate your satisfaction with the Spring semester's event lineup. (1 = Unsatisfied, 5 = Very Satisfied)",Optional: One event you wish we did that we haven't?,"Optional: If we did more community service, what type of service would actually interest you?"
0,7/20/2026 12:24:56,Rising Senior,10+,5,3,5,5,5,4,4,3,"Weekday evening, Friday, Saturday, Sunday",Too tired/burnt out,GroupMe (brotherchat/important announcements),4,Island Week,More animal shelter help
1,7/20/2026 12:33:20,Rising Senior,10+,4,4,4,5,4,3,3,5,"Weekday evening, Friday, Saturday, Sunday",Conflicts with class/work,GroupMe (brotherchat/important announcements),3,Dye tournament,NaN
2,7/20/2026 12:33:46,Rising Junior,10+,4,5,4,3,2,4,5,3,"Weekday evening, Friday, Saturday, Sunday",Too tired/burnt out,GroupMe (brotherchat/important announcements),4,NaN,NaN
3,7/20/2026 12:33:51,Rising Senior,10+,3,5,4,4,4,2,3,5,"Friday, Saturday, Sunday",Conflicts with class/work,In-person/word from other brothers,3,NaN,NaN
4,7/20/2026 12:33:53,Rising Junior,10+,4,4,4,3,3,4,2,3,"Weekday evening, Friday, Saturday",Not interested in event type,GroupMe (brotherchat/important announcements),3,NaN,NaN

# Data Cleaning / Prep #

In [25]:
# renaming columns for easier access
column_map = {
    'Timestamp': 'timestamp',
    'Class Year': 'class_year',
    'How many chapter events would you say you attended last semester? (This includes everything from B.O.B. pregames to events like Senior Sendoff)': 'events_attended',
    'Rank how likely you are to attend each type of event:    \n\nPregames (1 = NEVER, 5 = ALWAYS)': 'rating_pregames',
    'Postgames  (1 = NEVER, 5 = ALWAYS)': 'rating_postgames',
    'Socials/Mixers  (1 = NEVER, 5 = ALWAYS)': 'rating_socials',
    'Brotherhood Events (fam olympics, paintball, boat trip, etc.)\n(1 = NEVER, 5 = ALWAYS)': 'rating_brotherhood',
    'Philanthropy/Fundraising Events  \n(1 = NEVER, 5 = ALWAYS)': 'rating_philanthropy',
    'Professional/Networking Events\n(1 = NEVER, 5 = ALWAYS)': 'rating_professional',
    'Community Service Events\n(1 = NEVER, 5 = ALWAYS)': 'rating_community_service',
    'Alumni Events (pig dinner, etc.)\n(1 = NEVER, 5 = ALWAYS)': 'rating_alumni',
    'What day(s) for events work best for you? (Check all that apply)': 'preferred_days',
    "What's the #1 reason you'd skip an event?": 'reason_skip_event',
    'How do you usually hear about events?': 'event_communication',
    "Given the circumstances, rate your satisfaction with the  Spring semester's event lineup. (1 = Unsatisfied, 5 = Very Satisfied)": 'satisfaction_event_lineup',
    "Optional: One event you wish we did that we haven't?": 'wished_event',
    'Optional: If we did more community service, what type of service would actually interest you?': 'community_service_interest'
}

In [26]:
df = df.rename(columns=column_map)

In [27]:
df.columns

Index(['timestamp', 'class_year', 'events_attended', 'rating_pregames',
       'rating_postgames', 'rating_socials', 'rating_brotherhood',
       'rating_philanthropy', 'rating_professional',
       'rating_community_service', 'rating_alumni', 'preferred_days',
       'reason_skip_event', 'event_communication', 'satisfaction_event_lineup',
       'wished_event', 'community_service_interest'],
      dtype='str')

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   timestamp                   43 non-null     str
 1   class_year                  43 non-null     str
 2   events_attended             43 non-null     str
 3   rating_pregames             43 non-null     int64
 4   rating_postgames            43 non-null     int64
 5   rating_socials              43 non-null     int64
 6   rating_brotherhood          43 non-null     int64
 7   rating_philanthropy         43 non-null     int64
 8   rating_professional         43 non-null     int64
 9   rating_community_service    43 non-null     int64
 10  rating_alumni               43 non-null     int64
 11  preferred_days              43 non-null     str
 12  reason_skip_event           43 non-null     str
 13  event_communication         43 non-null     str
 14  satisfaction_event_lineup   43 non-null     int64
 15  wished_event                21 non-null     str
 16  community_service_interest  13 non-null     str
dtypes: int64(9), str(8)
memory usage: 5.8 KB

In [29]:
# Display value counts for categorical columns to understand the distribution of responses
for col in ['class_year', 'events_attended', 'preferred_days', 'reason_skip_event', 'event_communication']:
    print(col)
    print(df[col].value_counts())
    print()

class_year
class_year
Rising Sophomore    17
Rising Junior       15
Rising Senior       11
Name: count, dtype: int64

events_attended
events_attended
10+    29
7-9     6
4-6     4
0-3     4
Name: count, dtype: int64

preferred_days
preferred_days
Weekday evening, Friday, Saturday                               12
Weekday evening, Friday, Saturday, Sunday                        9
Friday, Saturday, Sunday                                         9
Weekday afternoon, Weekday evening, Friday, Saturday, Sunday     4
Weekday afternoon, Weekday evening, Friday, Saturday             3
Friday, Saturday                                                 3
Saturday, Sunday                                                 1
Weekday afternoon, Sunday                                        1
Weekday afternoon, Weekday evening, Saturday                     1
Name: count, dtype: int64

reason_skip_event
reason_skip_event
Conflicts with class/work       21
Not interested in event type    12
Too tired/burnt out              8
Cost                             1
Lazy af                          1
Name: count, dtype: int64

event_communication
event_communication
GroupMe (brotherchat/important announcements)    31
Chapter Meetings                                  8
In-person/word from other brothers                3
Personally texted from exec/committee members     1
Name: count, dtype: int64

In [30]:
# "Lazy af" was a free-text "Other" response. Folding it into "Too tired/burnt out" since it's semantically equivalent
# Judgement call: could have also kept as standalone "Other" category
df['reason_skip_event'] = df['reason_skip_event'].replace({'Lazy af': 'Too tired/burnt out'})

df['reason_skip_event'].value_counts()     # confirming merge was successful

reason_skip_event
Conflicts with class/work       21
Not interested in event type    12
Too tired/burnt out              9
Cost                             1
Name: count, dtype: int64

In [31]:
# preferred_days into 5 separate binary columns
day_dummies = df['preferred_days'].str.get_dummies(', ')
day_dummies.columns

Index(['Friday', 'Saturday', 'Sunday', 'Weekday afternoon', 'Weekday evening'], dtype='str')

In [32]:
# renaming dummy dolumns
day_dummies = day_dummies.rename(columns={
    'Weekday afternoon': 'pref_weekday_afternoon',
    'Weekday evening': 'pref_weekday_evening',
    'Friday': 'pref_friday',
    'Saturday': 'pref_saturday',
    'Sunday': 'pref_sunday'
})

df = pd.concat([df, day_dummies], axis=1)     # axis=1 is okay because row order and index remain the same
df.columns     # confirm 5 new pref_ columns are now attached

Index(['timestamp', 'class_year', 'events_attended', 'rating_pregames',
       'rating_postgames', 'rating_socials', 'rating_brotherhood',
       'rating_philanthropy', 'rating_professional',
       'rating_community_service', 'rating_alumni', 'preferred_days',
       'reason_skip_event', 'event_communication', 'satisfaction_event_lineup',
       'wished_event', 'community_service_interest', 'pref_friday',
       'pref_saturday', 'pref_sunday', 'pref_weekday_afternoon',
       'pref_weekday_evening'],
      dtype='str')

In [35]:
df.columns[df.columns.duplicated()]  # quick check; returns empty Index([]) if clean

Index([], dtype='str')

In [36]:
df[['preferred_days', 'pref_friday', 'pref_saturday', 'pref_sunday']].head()

,preferred_days,pref_friday,pref_saturday,pref_sunday
0,"Weekday evening, Friday, Saturday, Sunday",1,1,1
1,"Weekday evening, Friday, Saturday, Sunday",1,1,1
2,"Weekday evening, Friday, Saturday, Sunday",1,1,1
3,"Friday, Saturday, Sunday",1,1,1
4,"Weekday evening, Friday, Saturday",1,1,0

In [38]:
df.columns # make sure 22 columns now present and no duplicate columns

Index(['timestamp', 'class_year', 'events_attended', 'rating_pregames',
       'rating_postgames', 'rating_socials', 'rating_brotherhood',
       'rating_philanthropy', 'rating_professional',
       'rating_community_service', 'rating_alumni', 'preferred_days',
       'reason_skip_event', 'event_communication', 'satisfaction_event_lineup',
       'wished_event', 'community_service_interest', 'pref_friday',
       'pref_saturday', 'pref_sunday', 'pref_weekday_afternoon',
       'pref_weekday_evening'],
      dtype='str')